### ISSUE TITLE
After the OAuth token expiry, the applications stops receiving notifications from Salesforce Event Bus

### ISSUE THREAD

**Issue by vnmnm** [kdcllc/Bet.BuildingBlocks.SalesforceEventBus#6]
This is not an issue. I am seeking support.

I am using this application to understand how the Salesforce Event Bus works. In our Salesforce connected app, the grant type is set to password and we use username and password to get the access token. Accordingly, I added a new extension method to register the ResilientStreamingClient. The only change in this method is how I get the access token. I use the password grant type to get the access token as below:

services.AddSingleton<Func<AsyncExpiringLazy<AccessTokenResponse>>>(sp => () =>
{

    var salesforceConfig = sp.GetRequiredService<IOptions<SalesforceConfiguration>>().Value;
    TimeSpan.TryParse(salesforceConfig.TokenExpiration, out var tokenExperation);
    return new AsyncExpiringLazy<AccessTokenResponse>(async data =>
    {
        if (data.Result == null
            || DateTime.UtcNow > data.ValidUntil.Subtract(TimeSpan.FromSeconds(30)))
        {
            var nvc = new List<KeyValuePair<string, string>>();
            nvc.Add(new KeyValuePair<string, string>("grant_type", "password"));
            nvc.Add(new KeyValuePair<string, string>("client_id", salesforceConfig.ClientId));
            nvc.Add(new KeyValuePair<string, string>("client_secret", salesforceConfig.ClientSecret));
            nvc.Add(new KeyValuePair<string, string>("username", "myusername"));
            nvc.Add(new KeyValuePair<string, string>("password", "mypassword"));

            var req = new HttpRequestMessage(HttpMethod.Post, salesforceConfig.LoginUrl + salesforceConfig.OAuthUri)
            {
                Content = new FormUrlEncodedContent(nvc)
            };

            Console.WriteLine($"------------------------------------> Getting token at {DateTime.Now}");
            var response = await new HttpClient().SendAsync(req);
            var content = await response.Content.ReadAsStringAsync();
            var tokenResponse = JsonConvert.DeserializeObject<AccessTokenResponse>(content);

            Console.WriteLine($"------------------------------------> Got a new token at {DateTime.Now}");
            return new AsyncExpirationValue<AccessTokenResponse>
            {
                Result = tokenResponse,
                ValidUntil = DateTimeOffset.UtcNow.Add(tokenExperation)
            };
        }

        return data;
    });
});

This app runs fine and receives all events from the Event Bus until the OAuth access token expires. Once it expires, it doesn't throw any auth error and reconnect. Instead it stops receiving the events. After browsing through the code my understanding is when the token expires it throws an auth error and the BayeuxClient is recreated with a new token (from the AsyncExpiringLazy delegate). But it doesn't seem to be happening.

Just wanted to know if my understanding is correct and if I am missing anything in this case that it stops working after the token expires.

**Comment by kdcllc** [comment]
@vnmnm the reason the original code works is that `Polly` library is used to retry the call on failure of the token. Please refer to https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/a5379597b056a9f74655cb3870eebcb38319ebab/src/CometD.NetCore.Salesforce/StreamingClientExtensions.cs#L62

Here is the code you are missing
https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/a5379597b056a9f74655cb3870eebcb38319ebab/src/CometD.NetCore.Salesforce/StreamingClientExtensions.cs#L97

kdcllc

**Comment by vnmnm** [comment]
@kdcllc Thank you for your response. Apologies for not being specific earlier. I am not having any issues with getting the access token from Salesforce. The access token get works fine and the first subscribe call starts receiving events from the Event Bus without any issue.

But once this token expires, the subscription should fail with auth error and that triggers the `ErrorExtension_ConnectionError()` method which invalidates the current token and creates a new bayeuxClient with new access token and re-subscribes again. This might or might not return a new token depending on the `ValidUntil` property. I am referring below code snippet in CometD.netCore.Salesforce.
 
[https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/master/src/CometD.NetCore.Salesforce/ResilientStreamingClient.cs#L243](https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/master/src/CometD.NetCore.Salesforce/ResilientStreamingClient.cs#L243)

In my case, this extension never gets called and consequently the token never gets refreshed and the subscription never gets reconnected. It just stops receiving events from the Event Bus.

I tried adding Polly retry as suggested but the behavior is same. The access token is refreshed only in the `CreateBayeuxClient()` method and this method is called either during first time subscription to Event Bus or during any error (including auth error) in the `ErrorExtension_ConnectionError()` method.

So when exactly does the `ErrorExtension_ConnectionError()` gets called so that the token can be invalidated and a new token be generated and a new subscription can be created using the new token by unsubscribing from the old subscription?

**Comment by vnmnm** [comment]
@kdcllc I downloaded the latest version of this code and ran it by hard-coding the AccessToken value to "RandomTokenString" and the behavior is as below:

- It says successfully subscribed to the topic even with an invalid access token
- It does not throw any auth errors.
- It does not receive any change notifications from the Event Bus which is expected.
- If it does not throw any auth errors, then how does it re-subscribe when the token expires? Because reconnect is triggered from `ErrorExtension_ConnectionError()` method which is triggered on auth errors.

`return new AsyncExpiringLazy<AccessTokenResponse>(async data =>`

                {
                    return new AsyncExpirationValue<AccessTokenResponse>
                    {
                        Result = new AccessTokenResponse
                        {
                            AccessToken = "RamdomTokenString",
                            InstanceUrl = "https://testapp.my.salesforce.com",
                        },
                        ValidUntil = DateTimeOffset.UtcNow.Add(tokenExperation)
                    };
                });`

The output of the application is as below:

> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       Creating BayeuxClient ...
> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       BayeuxClient was created...
> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       Handshaking...
> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       Connected
> info: Bet.Salesforce.TestApp.Services.SalesforceEventBusHostedService[0]
>       StartAsync has been called.
> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       Handshaking...
> dbug: CometD.NetCore.Salesforce.ResilientStreamingClient[0]
>       Connected
> info: Bet.BuildingBlocks.SalesforceEventBus.EventBus[0]
>       Found match
> dbug: Bet.BuildingBlocks.SalesforceEventBus.EventBus[0]
>       /topic/mycustomtopic is subscribed with ReplayId: -1
> Application started. Press Ctrl+C to shut down.
> Hosting environment: Development
> info: Bet.Salesforce.TestApp.Services.SalesforceEventBusHostedService[0]
>       OnStarted has been called.

**Comment by tgobena** [comment]
Hi,

I am seeing the same error. @vnmnm or @kdcllc, did you get the solution related to this?

**Comment by vnmnm** [comment]
@tgobena Nope I haven't found any solution for this. It works as long as the token is valid. After that it does not automatically refresh the token. I have to stop and re-run the application as a work-around. I am wondering if there is any configuration that needs to be done on Salesforce side so that it returns the "authentication" error on the "meta/connect" channel.

**Comment by kdcllc** [comment]
@vnmnm  and @tgobena  we released the latest libraries and what our testing it solved the issue with reconnect. please let us know.

**Comment by vnmnm** [comment]
@kdcllc Thank you for your support. The reconnect works fine for me now.
